import RandomStuff.Basic
import RandomStuff.SimpleGraph.Utils
import RandomStuff.SimpleGraph.«01_HandshakeLemma».DoubleCounting
import RandomStuff.SimpleGraph.«01_HandshakeLemma».InductionOnNumberOfEdges
import RandomStuff.SimpleGraph.«01_HandshakeLemma».InductionOnNumberOfVertices
import RandomStuff.SimpleGraph.«02_NumberOfEdges».InductionOnNumberOfVertices
